// <auto-generated />
namespace Corcentric.LunchAndLearnBlog.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddPosts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPosts));
        
        string IMigrationMetadata.Id
        {
            get { return "201401281654365_AddPosts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
